[workspace]
members = ["api", "subscriber", "src-tauri", "test-fixture"]
resolver = "2"

[workspace.dependencies]
mdns-sd = "0.7.2"
tracing = "0.1.26"
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "feat/tracing2" }
tauri-build = { git = "https://github.com/tauri-apps/tauri", branch = "feat/tracing2" }
# tauri = "2.0.0-alpha.8"
# tauri-build = "2.0.0-alpha.4"